### PR TITLE
new: test current state of lookyloo repo on push

### PR DESCRIPTION
**Pull request by Felalex57**
Pull requests should be opened against the `main` branch. For more information on contributing to Lookyloo documentation, see the [Contributor Guidelines](https://www.lookyloo.eu/docs/main/contributor-guide.html).

## Type of change

**Description:**

new .yml file that set ups a Lookyloo instance that will be tested using pylookyloo

**Select the type of change(s) made in this pull request:**
- [ ] Bug fix *(non-breaking change which fixes an issue)*
- [x ] New feature *(non-breaking change which adds functionality)*
- [ ] Documentation *(change or fix to documentation)*

I'm not sure how this is going to work, maybe it is preferable to run splash with docker [like this](https://dev.to/mihinduranasinghe/using-docker-containers-in-jobs-github-actions-3eof)

### CODE REVIEW

**Comment by Rafiot** [comment]
I fought with github actions, it was a bit of a mess, but here is the commit with the changes: https://github.com/Lookyloo/lookyloo/commit/97098a13f952965e6b9414fcaf90dd828591efa7

**Comment by Felalex57** [comment]
Thats a lot more indeed. Do you know how I could easily test my .yml file? In my own fork maybe?

**Comment by Rafiot** [comment]
Testing the file is a bit of a problem, but it you directly edit it via github (on your fork), it will at least tell you if the syntax is correct. But to check if the scripts you're executing are working, there is no other way than comiting a change and waiting for the build to finish. It is pretty annoying, but that's the only way I know how to do that.

For the tests themselves, you can simply run the test script on your own machine and check if it works against your local lookyloo instance.

**Comment by Felalex57** [comment]
Okay that's indeed what I thought. Thanks :)

**Pull request closed without merging**
